# Generated by Django 4.1.2 on 2022-10-17 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0003_datasetdb_rename_bot_say_botsessiondb_prev_question_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="botsessiondb",
            name="prev_question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="db.datasetdb",
            ),
        ),
    ]
